server:
  port: 8000  # The Single Entry Point

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. BENEFICIARY SERVICE
        - id: beneficiary-service
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/api/v1/beneficiaries/**

        # 2. LEDGER SERVICE
        - id: ledger-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/v1/ledger/**

        # 3. KYC SERVICE
        - id: kyc-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/v1/kyc/**